mimizik_app_fb_token:
    path:  /token
    defaults: { _controller: SpicyAppBundle:Facebook:token }
    
mimizik_app_fb_login:
    path:  /login
    defaults: { _controller: SpicyAppBundle:Facebook:login }
    
mimizik_app_fb_test:
    path:  /test
    defaults: { _controller: SpicyAppBundle:Facebook:test }