<?php

namespace Spicy\SiteBundle\Entity;

/**
 * ApprovalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovalRepository extends \Doctrine\ORM\EntityRepository
{
}
