spicy_ranking:
    resource: "@SpicyRankingBundle/Resources/config/routing.yml"
    prefix:   /

spicy_flux:
    resource: "@SpicyFluxBundle/Resources/config/routing.yml"
    prefix:   /flux/

spicy_user:
    resource: "@SpicyUserBundle/Resources/config/routing.yml"
    prefix:   /

spicy_site:
    resource: "@SpicySiteBundle/Resources/config/routing.yml"
    prefix:   /
spicy_admin:
    resource: "@SpicySiteBundle/Resources/config/routing_admin.yml"
    prefix:   /admin/
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
mimizik_tag:
    resource: "@SpicyTagBundle/Resources/config/routing/hashtag.yml"
    prefix:   /hashtags/