jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Spicy\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_MODERATEUR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        
        main:
            id: fos_user.user_provider.username        
    
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        main:
#            pattern: ^/
#            anonymous: true
#            provider: main
#            form_login:
#                login_path: fos_user_security_login
#                check_path: fos_user_security_check
#                use_referer: true
#            logout:
#                path: fos_user_security_logout
#                target: /
#        secured_area:
##            pattern:    ^/demo/secured/
#            oauth:
#                resource_owners:
#                    facebook:      /login_social
#                login_path:        /login
#                failure_path:      /login
#                oauth_user_provider:
#                    service: mimizik.user_provider.service
#
#            # Turn on anonymous for testings need.
#            anonymous: ~
        main:
            pattern: ^/
            provider: main
            form_login:
#                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: mimizik.user_provider.service
            logout:       true
            anonymous:    true

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                key: "mimizik_remember_me"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
            
    access_control:
        - { path: ^/approval, roles: [ROLE_ADMIN,ROLE_CONTRIBUTOR] }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }