parameters:
    #home
#    database_driver:   pdo_mysql
#    database_host:     127.0.0.1
#    database_port:     ~
#    database_name:     mimizik
#    database_user:     root
#    database_password: ~

#    taf
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     8889
    database_name:     mimizik
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       'mail.mimizik.com'
    mailer_user:       'franchesco971@mimizik.com'
    mailer_password:   'franches971'
    mailer_port:       465
    
    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt

