parameters:
#    spicy_site.example.class: Spicy\SiteBundle\Example
    nbMainVideo: 5
    nbResultVideoIndex: 9
    nbResultVideo: 16
    
    nbArtisteAffiche: 20
    nbSuggestion: 10
    nbGenreAffiche: 10

services:
    spicy_site.parseurXML:
        class: Spicy\SiteBundle\ParseurXML\ParseurNews
        arguments: ["http://www.reggaefrance.com/news.xml"]
#    spicy_site.example:
#        class: %spicy_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
