parameters:
#    spicy_itw.example.class: Spicy\ITWBundle\Example

services:
#    spicy_itw.example:
#        class: %spicy_itw.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
