<?php

namespace Spicy\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ApprovalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovalRepository extends EntityRepository
{
    public function getAll($page, $nbOccurences)
    {
        $qb = $this->createQueryBuilder('a')
                ->setFirstResult(($page-1) * $nbOccurences)
                ->setMaxResults($nbOccurences)
                ->orderBy('a.requestDate', 'DESC')
                // ->addOrderBy('a.approvalDate', 'ASC')
                ;
        
        $query = $qb->getQuery();
        return new Paginator($query);
    }

    public function getCount()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('COUNT(a.id)');
        
        return $qb->getQuery()->getSingleScalarResult();
    }
}
