mimizik_ranking_show:
    path:  /show/{type_id}/{id}
    defaults: { _controller: SpicyRankingBundle:Ranking:show }
    requirements: 
        id: \d+
        type_id: \d+
        
mimizik_ranking_last_show:
    path:  /last
    defaults: { _controller: SpicyRankingBundle:Ranking:showLast }
    requirements: 
        id: \d+        
    
mimizik_ranking_index:
    path:  /month/{page}
    defaults: { _controller: SpicyRankingBundle:Ranking:index, page: 1 }
    
mimizik_year_ranking_index:
    path:  /year/{page}
    defaults: { _controller: SpicyRankingBundle:Ranking:indexYear, page: 1 }
    
mimizik_ajax_ranking_side:
    path:  /side/{type}
    defaults: { _controller: SpicyRankingBundle:Ranking:ajaxRankingSide }