spicy_site_flux_videos:
    path: /videos
    defaults: { _controller: SpicyFluxBundle:Flux:fluxVideos }    
spicy_site_flux_videos_twitter:
    path: /videos_twitter
    defaults: { _controller: SpicyFluxBundle:Flux:fluxVideosTwitter }
spicy_site_flux_retro:
    path: /retro
    defaults: { _controller: SpicyFluxBundle:Flux:fluxRetro }
spicy_site_flux_retro_twitter:
    path: /retro_twitter
    defaults: { _controller: SpicyFluxBundle:Flux:fluxRetroTwitter }
spicy_site_flux_artistes:
    path: /artistes
    defaults: { _controller: SpicyFluxBundle:Flux:fluxArtistes }
spicy_site_flux_index:
    path: /index
    defaults: { _controller: SpicyFluxBundle:Flux:fluxIndex }
mimizik_flux_videos_top:
    path: /videos_top
    defaults: { _controller: SpicyFluxBundle:Flux:fluxVideosTop }
mimizik_flux_videos_top_twitter:
    path: /videos_top_twitter
    defaults: { _controller: SpicyFluxBundle:Flux:fluxVideosTopTwitter }
mimizik_flux_lyrics:
    path: /lyrics
    defaults: { _controller: SpicyFluxBundle:Flux:fluxLyrics }
mimizik_flux_itw:
    path: /itw
    defaults: { _controller: SpicyFluxBundle:Flux:fluxITW }
mimizik_flux_videos_json_page:
    path: /videos_json/{page}
    defaults: { _controller: SpicyFluxBundle:Flux:fluxVideosJson, page: 1 }
    requirements: 
        id: \d+
        
mimizik_flux_videos_content_studio:
    path: /videos_content_studio
    defaults: { _controller: SpicyFluxBundle:Flux:fluxVideosContentStudio }  
