parameters:
#    spicy_flux.example.class: Spicy\FluxBundle\Example

services:
    mimizik.twitter:
        class: Spicy\FluxBundle\Services\Twitter
    mimizik.service.flux:
        class: Spicy\FluxBundle\Services\fluxService
