spicy_site_approval:
    resource: "@SpicySiteBundle/Resources/config/routing/approval.yml"
    prefix:   /approval

mimizik_site_video:
    resource: "@SpicySiteBundle/Resources/config/routing/video.yml"
    prefix:   /video

mimizik_site_artist:
    resource: "@SpicySiteBundle/Resources/config/routing/artist.yml"
    prefix:   /artist

mimizik_site_search:
    resource: "@SpicySiteBundle/Resources/config/routing/search.yml"
    prefix:   /search    

spicy_site_homepage:
    path:  /{page}
    defaults: { _controller: SpicySiteBundle:Site:index,page: 1 }
    requirements: 
        page: \d+
mimizik_homepage_ajax:
    path:  /ajax/{page}
    defaults: { _controller: SpicySiteBundle:Site:indexSuiteAjax,page: 1 }
    requirements: 
        page: \d+              
spicy_site_video_slug:
    path:  /video/{id}/{slug}
    defaults: { _controller: SpicySiteBundle:Site:show }
    requirements: 
        id: \d+
spicy_site_video:
    path:  /video/{id}
    defaults: { _controller: SpicySiteBundle:Site:show }
    requirements: 
        id: \d+
        
spicy_site_artistes:
    path: /artistes/{page}
    defaults: { _controller: SpicySiteBundle:Site:indexArtiste, page: 1 }
    requirements: 
        page: \d+
spicy_site_artiste_slug:
    path: /artiste/{id}/{slug}/{page}
    defaults: { _controller: SpicySiteBundle:Site:showArtiste, page: 1 }
    requirements:
        slug: "[a-zA-Z0-9-_]+"
        id: \d+
        page: \d+
spicy_site_artiste:
    path: /artiste/{id}
    defaults: { _controller: SpicySiteBundle:Site:showArtiste }
    requirements: 
        id: \d+        
mimizik_show_artiste_js:
    path: /artiste/
    defaults: { _controller: SpicySiteBundle:Site:showArtiste }
        
spicy_site_genres:
    path: /genres/{page}
    defaults: { _controller: SpicySiteBundle:Site:indexGenre, page: 1 }
    requirements:
        page: \d+
spicy_site_genre_old:
    path: /genre/{slug}-{id}
    defaults: { _controller: SpicySiteBundle:Site:showGenre, page: 1 }
    requirements:
        slug: "[a-zA-Z-]+"
        id: \d+
spicy_site_genre:
    path: /genre/{id}/{page}/{slug}
    defaults: { _controller: SpicySiteBundle:Site:showGenre, page: 1 }
    requirements:
        slug: "[a-zA-Z-]+"
        id: \d+
        
# spicy_site_news:
#     path: /news
#     defaults: { _controller: SpicySiteBundle:Site:News }
spicy_site_credits:
    path: /credits
    defaults: { _controller: SpicySiteBundle:Site:Credits }
spicy_site_contact:
    path: /contact
    defaults: { _controller: SpicySiteBundle:Site:contact }
mimizik_site_contact_approval:
    path: /contact/approval
    defaults: { _controller: SpicySiteBundle:Site:contactApproval }

spicy_site_test:
    path: /test
    defaults: { _controller: SpicySiteBundle:Site:Test }
    
spicy_site_liste_artiste:
    path: /list_artiste
    defaults: { _controller: SpicySiteBundle:Site:listArtiste }
spicy_site_liste_alpha:
    path: /list_alpha
    defaults: { _controller: SpicySiteBundle:Site:listAlpha }
spicy_site_alphabet:
    path: /alphabet
    defaults: { _controller: SpicySiteBundle:Site:alphabet }
      
spicy_site_redirect_youtube:
    path: /user/mimizikcom
    defaults: { _controller: SpicySiteBundle:Site:redirectYoutube }
mimizik_redirect_youtube_videos:
    path: /user/mimizikcom/{videos}
    defaults: { _controller: SpicySiteBundle:Site:redirectYoutube }
mimizik_site_redirect_youtube:
    path: /channel/{url}
    defaults: { _controller: SpicySiteBundle:Site:redirectYoutube }
mimizik_site_redirect_youtube_videos:
    path: /channel/{url}/{plus}
    defaults: { _controller: SpicySiteBundle:Site:redirectYoutube }
mimizik_site_redirect_feedback:
    path: /plugins/feedback.php
    defaults: { _controller: SpicySiteBundle:Site:redirectFeedback }
mimizik_redirect_wp:
    path: /wp-login.php
    defaults: { _controller: SpicySiteBundle:Site:redirectDefault }
mimizik_redirect_hashta:
    path: /hashta
    defaults: { _controller: SpicySiteBundle:Site:redirectDefault }    
    
mimizik_tops:
    path:  /tops/{page}
    defaults: { _controller: SpicySiteBundle:Site:showTops, page: 1 }
    
mimizik_genres_menu:
    path: /genres_menu
    defaults: { _controller: SpicySiteBundle:Site:Genres }
    
mimizik_paroles_slug:
    path:  /video/paroles/{id}/{slug}
    defaults: { _controller: SpicySiteBundle:Site:show, referrer:'lyrics' }
    requirements: 
        id: \d+
        
# mimizik_paroles_show:
#     path: /paroles/{id}/{slug}
#     defaults: { _controller: SpicyLyricsBundle:Lyrics:show }
#     requirements: 
#         id: \d+
        
mimizik_last_itw_show:
    path: /itw/{id_artiste}/{slug_artiste}
    defaults: { _controller: SpicySiteBundle:Site:showLastInterview }
    requirements: 
        id: \d+
        
# mimizik_itw_show:
#     path: /itw/{id}/{slug_artiste}
#     defaults: { _controller: SpicySiteBundle:Site:showInterview }
#     requirements: 
#         id: \d+

mimizik_video_json:
    path:  /video/json/{id}
    defaults: { _controller: SpicySiteBundle:Site:videoJson }
    requirements: 
        id: \d+        
