spicy_admin_home:
    path:  /
    defaults: { _controller: SpicySiteBundle:Admin:index }
spicy_admin_home_video:
    path:  /video/{page}
    defaults: { _controller: SpicySiteBundle:Admin:homeVideo,page: 1 }
    requirements: 
        page: \d+
spicy_admin_add_video:
    path:  /add_video
    defaults: { _controller: SpicySiteBundle:Admin:addVideo }
spicy_admin_update_video:
    path:  /update_video/{id}
    defaults: { _controller: SpicySiteBundle:Admin:updateVideo }
    requirements:
        id: \d+
spicy_admin_delete_video:
    path:  /delete_video/{id}
    defaults: { _controller: SpicySiteBundle:Admin:deleteVideo }
    requirements:
        id: \d+   
        
spicy_admin_home_artiste:
    path:  /artiste/{page}
    defaults: { _controller: SpicySiteBundle:Admin:homeArtiste,page: 1 }
    requirements: 
        page: \d+
spicy_admin_add_artiste:
    path:  /add_artiste
    defaults: { _controller: SpicySiteBundle:Admin:addArtiste }
spicy_admin_update_artiste:
    path:  /update_artiste/{id}
    defaults: { _controller: SpicySiteBundle:Admin:updateArtiste }
    requirements:
        id: \d+
spicy_admin_delete_artiste:
    path:  /delete_artiste/{id}
    defaults: { _controller: SpicySiteBundle:Admin:deleteArtiste }
    requirements:
        id: \d+
        
spicy_admin_home_type_video:
    path:  /type_video
    defaults: { _controller: SpicySiteBundle:Admin:homeType_video }
spicy_admin_home_genre_musical:
    path:  /genre_musical
    defaults: { _controller: SpicySiteBundle:Admin:homeGenre_musical }
spicy_admin_add_genre_musical:
    path:  /add_genre_musical
    defaults: { _controller: SpicySiteBundle:Admin:addGenre_musical }
spicy_admin_update_genre_musical:
    path:  /update_genre_musical/{id}
    defaults: { _controller: SpicySiteBundle:Admin:updateGenre_musical }
    requirements:
        id: \d+
spicy_admin_delete_genre_musical:
    path:  /delete_genre_musical/{id}
    defaults: { _controller: SpicySiteBundle:Admin:deleteGenre_musical }
    requirements:
        id: \d+

spicy_admin_add_type_video:
    path:  /add_type_video
    defaults: { _controller: SpicySiteBundle:Admin:addType_video }
spicy_admin_update_type_video:
    path:  /update_type_video/{id}
    defaults: { _controller: SpicySiteBundle:Admin:updateType_video }
    requirements:
        id: \d+
spicy_admin_delete_type_video:
    path:  /delete_type_video/{id}
    defaults: { _controller: SpicySiteBundle:Admin:deleteType_video }
    requirements:
        id: \d+
        
spicy_admin_csv:
    path: /csv
    defaults: { _controller: SpicySiteBundle:Admin:csv }

    
admin_hashtag:
    path:  /hashtags
    defaults: { _controller: SpicyTagBundle:Hashtag:index }
    
# admin_hashtag_new:  
#     path:  /hashtag/new
#     defaults: { _controller: SpicyTagBundle:Hashtag:new }
    
admin_hashtag_new_modal:  
    path:  /hashtag/new_modal
    defaults: { _controller: SpicyTagBundle:Hashtag:new_modal }
    
admin_hashtag_new_modal_update:  
    path:  /hashtag/new_modal_update/{id}
    defaults: { _controller: SpicyTagBundle:Hashtag:new_modal_update }
    requirements:
        id: \d+
    
admin_hashtag_create_modal:  
    path:  /hashtag/create_modal
    defaults: { _controller: SpicyTagBundle:Hashtag:create_modal }
    
admin_hashtag_create_modal_update:  
    path:  /hashtag/create_modal_update/{id}
    defaults: { _controller: SpicyTagBundle:Hashtag:create_modal_update }
    requirements:
        id: \d+
    
# admin_hashtag_create:  
#     path:  /hashtag/create
#     defaults: { _controller: SpicyTagBundle:Hashtag:create }
    
admin_hashtag_edit:
    path:  /hashtag/edit/{id}
    defaults: { _controller: SpicyTagBundle:Hashtag:edit }
    requirements:
        id: \d+
  
admin_hashtag_delete:
    path:  /hashtag/delete/{id}
    defaults: { _controller: SpicyTagBundle:Hashtag:delete }
    requirements:
        id: \d+
        
admin_add_video_youtube:
    path:  /add_video_youtube
    defaults: { _controller: SpicySiteBundle:Admin:addVideoYoutube }
    
admin_collaborateur_new_modal:  
    path:  /collaborateur/new_modal
    defaults: { _controller: SpicySiteBundle:Admin:modalNewCollaborateur }
    
admin_collaborateur_create_modal:  
    path:  /collaborateur/create_modal
    defaults: { _controller: SpicySiteBundle:Admin:modalCreateCollaborateur }  
        
admin_test_fb:
    path:  /test/fb
    defaults: { _controller: SpicySiteBundle:Admin:testFB }
