parameters:
#    spicy_site.example.class: Spicy\SiteBundle\Example
    nbMainVideo: 5
    nbResultVideoIndex: 9
    nbResultVideo: 16
    
    nbArtisteAffiche: 20
    nbSuggestion: 10
    nbGenreAffiche: 10
    nbVideosGenreAffiche: 20

services:
    spicy_site.parseurXML:
        class: Spicy\SiteBundle\ParseurXML\ParseurNews
        arguments: ["http://www.reggaefrance.com/news.xml"]
    mimizik.social:
        class: Spicy\SiteBundle\Services\Social
    mimizik.tools:
        class: Spicy\SiteBundle\Services\Tools
        arguments: [ "@mailer" ]
    mimizik.videoService:
        class: Spicy\SiteBundle\Services\VideoService
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            logger: "@logger"
            youtubeParseur: "@mimizik.parseur.youtube"
        tags:
        - { name: monolog.logger, channel: mimizik }
    mimizik.parseur.youtube:
        class: Spicy\SiteBundle\Services\ParseurXMLYoutube
    mimizik.youtube.api:
        class: Spicy\SiteBundle\Services\YoutubeAPI
    mimizik.twig.name.extension:
        class: Spicy\SiteBundle\Twig\NameExtension
        arguments: [ "@router" ]
        tags:
            - { name: twig.extension }
