mimizik_hashtag:
    path:  /
    defaults: { _controller: "SpicyTagBundle:Hashtag:index" }

#hashtag_show:
#    path:  /{id}/show
#    defaults: { _controller: "SpicyTagBundle:Hashtag:show" }
    
mimizik_tag_show:
    path:  /{tag}/{page}
    defaults: { _controller: SpicyTagBundle:Hashtag:showTag, page: 1 }
    requirements:
        tag: "[a-zA-Z0-9-_]+"    

hashtag_new:
    path:  /new
    defaults: { _controller: "SpicyTagBundle:Hashtag:new" }

hashtag_create:
    path:  /create
    defaults: { _controller: "SpicyTagBundle:Hashtag:create" }
    requirements: { _method: post }

# hashtag_edit:
#     path:  /{id}/edit
#     defaults: { _controller: "SpicyTagBundle:Hashtag:edit" }

# hashtag_update:
#     path:  /{id}/update
#     defaults: { _controller: "SpicyTagBundle:Hashtag:update" }
#     requirements: { _method: post|put }

# hashtag_delete:
#     path:  /{id}/delete
#     defaults: { _controller: "SpicyTagBundle:Hashtag:delete" }
#     requirements:
#         _method: post|delete
#         id: \d+
    
