parameters:
#    spicy_lyrics.example.class: Spicy\LyricsBundle\Example

services:
#    spicy_lyrics.example:
#        class: %spicy_lyrics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
