parameters:
#    spicy_user.example.class: Spicy\UserBundle\Example

services:
    mimizik.user_provider.service:
        class: Spicy\UserBundle\Service\UserProvider
        arguments: ["@fos_user.user_manager",{facebook: 'facebookId',google: 'googleId'}]
