parameters:
#    spicy_user.example.class: Spicy\UserBundle\Example

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # mimizik.user_provider.service:
    #     class: Spicy\UserBundle\Service\UserProvider
    #     # arguments: ["@fos_user.user_manager",{facebook: 'facebookId',google: 'googleId'}]
    #     arguments:
    #         - '@fos_user.user_manager'
    #         - [facebook : 'facebookId', google : 'googleId']
                
