<?php

namespace Spicy\LyricsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArtisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LyricsRepository extends EntityRepository
{
    public function getOrdered($video)
    {
        $qb = $this->createQueryBuilder('l')
                ->join('l.paragraphs', 'p')
                ->join('l.title', 't')
                ->where('t.id=:video')
                ->setParameter('video', $video->getId())
                ->orderBy('p.position');
        
        $query = $qb->getQuery();
        return $query->getOneOrNullResult();
    }
    
    public function getAll($nb)
    {
        $qb = $this->createQueryBuilder('l')
             ->setFirstResult(0)
             ->setMaxResults($nb)
             ->addOrderBy('v.createdAt','DESC');
        
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
