mimizik_app_fb_token:
    pattern:  /token
    defaults: { _controller: SpicyAppBundle:Facebook:token }
    
mimizik_app_fb_login:
    pattern:  /login
    defaults: { _controller: SpicyAppBundle:Facebook:login }
    
mimizik_app_fb_test:
    pattern:  /test
    defaults: { _controller: SpicyAppBundle:Facebook:test }