mimizik_ranking_show:
    pattern:  /show/{type_id}/{id}
    defaults: { _controller: SpicyRankingBundle:Ranking:show }
    requirements: 
        id: \d+
        type_id: \d+
        
mimizik_ranking_last_show:
    pattern:  /last
    defaults: { _controller: SpicyRankingBundle:Ranking:showLast }
    requirements: 
        id: \d+        
    
mimizik_ranking_index:
    pattern:  /month/{page}
    defaults: { _controller: SpicyRankingBundle:Ranking:index,page: 1 }
    
mimizik_year_ranking_index:
    pattern:  /year/{page}
    defaults: { _controller: SpicyRankingBundle:Ranking:indexYear,page: 1 }