parameters:
    app_fb_id: 729891760354276
    app_fb_secret: f99b1e647c6db07975a37cc287c0d91b
    app_fb_graph_version: v2.5
    app_fb_page_id: 105385689672394

services:
    mimizik.app.facebook.manager:
        class: Spicy\AppBundle\Services\FacebookManager
        arguments:
            container: "@service_container"
            logger: "@logger"
    mimizik.publish.service:
        class: Spicy\AppBundle\Services\PublishService
        arguments:
            router: "@router"
            videoService: "@mimizik.videoService"
            facebookManager : "@mimizik.app.facebook.manager"
            em: "@doctrine.orm.entity_manager"
            session: "@session"
            
