hashtag:
    pattern:  /
    defaults: { _controller: "SpicyTagBundle:Hashtag:index" }

#hashtag_show:
#    pattern:  /{id}/show
#    defaults: { _controller: "SpicyTagBundle:Hashtag:show" }
    
mimizik_tag_show:
    pattern:  /{tag}/{page}
    defaults: { _controller: SpicyTagBundle:Hashtag:showTag, page: 1 }
    requirements:
        tag: "[a-zA-Z0-9-_]+"    

hashtag_new:
    pattern:  /new
    defaults: { _controller: "SpicyTagBundle:Hashtag:new" }

hashtag_create:
    pattern:  /create
    defaults: { _controller: "SpicyTagBundle:Hashtag:create" }
    requirements: { _method: post }

hashtag_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SpicyTagBundle:Hashtag:edit" }

hashtag_update:
    pattern:  /{id}/update
    defaults: { _controller: "SpicyTagBundle:Hashtag:update" }
    requirements: { _method: post|put }

hashtag_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SpicyTagBundle:Hashtag:delete" }
    requirements: { _method: post|delete }
