<?php

namespace Spicy\RankingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingRepository extends EntityRepository
{
    public function getLastRanking() 
    {
        $qb = $this->createQueryBuilder('r')
                ->join('r.videoRanking', 'vr')
                ->orderBy('r.dateRanking')
                ->addSelect('vr');
        
        return $qb->getQuery()->getSingleResult();
    }
}
