<?php

namespace Spicy\RankingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Spicy\RankingBundle\Entity\Ranking;
use Spicy\SiteBundle\Entity\Video;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRankingRepository extends EntityRepository
{
    public function getOne(Video $video, Ranking $ranking) 
    {
        $qb = $this->createQueryBuilder('vr')
                ->where('vr.video=:video')
                ->andWhere('vr.ranking=:ranking')
                ->setParameter('video', $video->getId())
                ->setParameter('ranking', $ranking->getId());
        
        return $qb->getQuery()->getOneOrNullResult();
    }
}
