<?php

namespace Spicy\TagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HashtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashtagRepository extends EntityRepository
{
    public function getById($id) 
    {
        
    }
}
